aloelabs/aloe-frontend

- earn/src/components/borrow/modal/NewSmartWalletModal.tsx
- earn/src/data/MarginAccount.ts
- earn/src/pages/BorrowPage.tsx
- earn/src/pages/LendPage.tsx
- shared/src/components/common/Pagination.tsx
As the title suggests, this PR improves the existing input for choosing a pair for a new smart wallet. Instead of relying on a dropdown with a lot of options that cause the user to have to scroll, and rather than work to make the dropdown better in this scenario (for now), we decided to create a more custom solution. This required a slight modification to existing components, but there should be no visible changes to any of them. Below is an image of the updated component:
> Improving the smart wallet input

- earn/src/components/portfolio/modal/EarnInterestModal.tsx
- earn/src/components/portfolio/modal/SendCryptoModal.tsx
- earn/src/components/portfolio/modal/WithdrawModal.tsx
The icons weren't being used anymore.
> Removing icons from modals

- prime/src/data/actions/Actions.ts
A bit of tidying up. Removing some redundant omissions.
> Cleaning up data types

- prime/src/components/borrow/ManageAccountWidget.tsx
- prime/src/components/borrow/actions/UniswapAddLiquidityActionCard.tsx
- prime/src/components/common/TokenAmountInput.tsx
- prime/src/data/RateModel.ts
- prime/src/pages/BorrowActionsPage.tsx
Fixing bugs with switching between tokens in the add liquidity action card. Removing console logs as well.
> Fixing bugs with add liquidity action card

- earn/src/components/borrow/modal/AddCollateralModal.tsx
- earn/src/components/borrow/modal/BorrowModal.tsx
- earn/src/components/borrow/modal/RepayModal.tsx
- earn/src/pages/BorrowPage.tsx
Adding logic to avoid needlessly fetching data. This will help us keep the total number of requests down which will benefit our users through quicker load times and us through sending fewer requests.
> Optimizing borrow page by reducing requests

- prime/src/components/borrow/ManageAccountTransactionButton.tsx
- prime/src/components/borrow/ManageAccountWidget.tsx
- prime/src/pages/BorrowActionsPage.tsx
As the title suggests, I am making the logic that prevents US users from using prime.
> Adding another layer of security to ensure only users outside of the can use prime

- earn/src/connector/WagmiProvider.tsx
- earn/src/pages/PortfolioPage.tsx
- prime/src/connector/WagmiProvider.tsx
- shared/src/components/navbar/ChainSelector.tsx
Adding logic to make the page refresh when switching chains. Cleaning up old code.
> Improving logic for switching chains and cleaning up code

- prime/src/components/borrow/ManageAccountTransactionButton.tsx
- prime/src/components/borrow/ManageAccountWidget.tsx
- prime/src/pages/BorrowAccountsPage.tsx
Adding a refresh on the accounts page after a user creates a new margin account.
Adding a more proper refetch to prime logic.
> Adding proper refetch to prime, adding refresh

- prime/src/App.tsx
- prime/src/components/borrow/ManageAccountTransactionButton.tsx
- prime/src/components/borrow/uniswap/LiquidityChartPlaceholder.tsx
- prime/src/util/Uniswap.ts
Fixing a few bugs, such as a lack of a `+ 1` for the ante, a lack of a uniswap v3 subgraph URL for arbitrum (sadly the only one I found doesn't support our graphs, even uniswap doesn't have these graphs on arbitrum),  and cleaning up the liquidity chart preview to fit correctly at all sizes.
> Fixing some bugs found while adding arbitrum

- earn/src/data/TokenData.ts
- prime/src/data/TokenData.ts
As the title suggests, I am adding tether to optimism for a new pool Hayden plans on adding.
> Adding tether to optimism

- earn/src/components/borrow/modal/AddCollateralModal.tsx
- earn/src/components/borrow/modal/RemoveCollateralModal.tsx
- earn/src/components/borrow/modal/tab/AddCollateralTab.tsx
Adding health bars to more borrow modals on earn. These are styled the same way as the previous health bars from the borrow modal.
> Adding more health bars

- earn/src/components/borrow/BorrowGraph.tsx
- earn/src/pages/BorrowPage.tsx
Interpolates between data points (fetched from Etherscan) so that we get evenly spaced points on the graph for IV and CF
> Interpolate to get evenly-spaced points on IV/CF graph

- earn/src/components/portfolio/modal/SendCryptoModal.tsx
Updating logic to utilize `Big`s whenever possible. Additionally, I am adding proper gas estimation.
> Fixing numeric logic and adding proper gas estimation

- earn/src/components/borrow/modal/RemoveCollateralModal.tsx
- earn/src/components/borrow/modal/tab/AddCollateralTab.tsx
- earn/src/components/lend/modal/content/WithdrawModalContent.tsx
- shared/src/abis/Borrower.ts
- shared/src/abis/ERC20.ts
- shared/src/abis/Lender.ts
- shared/src/abis/MarginAccount.ts
- shared/src/data/GoodNumber.ts
Updating two more modals to utilize GN. I had to make a few temporary tradeoffs by adding `fromNumber` and `toNumber` to accommodate logic that has not yet moved to GN. I also fixed an existing bug with health calculation which caused it to only take one asset into account on one of the modals.
> Moving more numeric logic to GN

- prime/src/data/MarginAccount.ts
- prime/src/pages/BorrowAccountsPage.tsx
> Starting to remove our etherscan api dependency on prime

- earn/src/util/Env.ts
- prime/src/App.tsx
- prime/src/util/Env.ts
- shared/src/util/Utils.ts
This enables us to enable or disable certain features while in development and testing.
> Adding util to detect if dev or prod environment

- prime/src/components/borrow/ManageAccountWidget.tsx
- prime/src/components/borrow/MarginAccountCard.tsx
- prime/src/components/borrow/uniswap/UniswapPositionsTable.tsx
- prime/src/data/BalanceSheet.ts
- prime/src/data/Balances.ts
- prime/src/data/MarginAccount.ts
- prime/src/data/MarketInfo.ts
- prime/src/data/actions/ActionOperators.ts
- prime/src/pages/BorrowActionsPage.tsx
- prime/src/util/ComputeLiquidationThresholdUtils.ts
- prime/src/util/Uniswap.ts
- shared/src/data/GoodNumber.test.ts
- shared/src/data/GoodNumber.ts
- shared/src/util/Numbers.ts
Builds off of #418. This PR aims to move more math from Bigs, JSBIs, and numbers into a more unified format akin to the math on the contracts.
> Adding more usages of GN to prime

- prime/src/components/borrow/ManageAccountTransactionButton.tsx
- prime/src/components/borrow/ManageAccountWidget.tsx
- prime/src/components/borrow/MarginAccountCard.tsx
- prime/src/components/borrow/actions/AloeAddMarginActionCard.tsx
- prime/src/components/borrow/actions/AloeBorrowActionCard.tsx
- prime/src/components/borrow/actions/AloeRepayActionCard.tsx
- prime/src/components/borrow/actions/AloeWithdrawActionCard.tsx
- prime/src/components/borrow/actions/UniswapAddLiquidityActionCard.tsx
- prime/src/components/borrow/actions/UniswapRemoveLiquidityActionCard.tsx
- prime/src/components/borrow/actions/UniswapSwapActionCard.tsx
- prime/src/components/borrow/uniswap/UniswapPositionsTable.tsx
- prime/src/data/BalanceSheet.ts
- prime/src/data/Balances.ts
- prime/src/data/MarginAccount.ts
- prime/src/data/MarketInfo.ts
- prime/src/data/actions/ActionArgs.ts
- prime/src/data/actions/ActionOperators.ts
- prime/src/pages/BorrowActionsPage.tsx
- prime/src/util/ComputeLiquidationThresholdUtils.ts
- prime/src/util/Uniswap.ts
- shared/src/data/GoodNumber.test.ts
- shared/src/data/GoodNumber.ts
- shared/src/util/Numbers.ts
Builds off of #425. This PR adds GN usage to prime action cards.
> Updating prime action cards to use GN

- prime/src/components/borrow/ManageAccountWidget.tsx
Adding a warning when a user's actions put them near liquidation.
> Adding health warning to prime

- earn/src/components/borrow/UniswapPositionList.tsx
Refactoring the uniswap position list making it more straightforward. Additionally, I made it so that uniswap positions appear empty before loading rather than not showing at all to improve the loading appearance and mitigate layout shifting.
> Simplifying uniswap position card logic

- prime/src/data/BalanceSheet.ts
Removing an unnecessary argument that was not being used.
> Removing redundant arg

- .github/workflows/test.yml
Adding an initial GitHub action to test.
> Adding a GitHub action to test

- earn/src/components/lend/LendPairCardPlaceholder.tsx
- earn/src/pages/LendPage.tsx
Adding a lending card placeholder that shows the shimmer effect while the lending cards are loading on the markets page.
> Adding a lend pair card placeholder

- shared/src/util/Numbers.test.ts
- shared/src/util/Numbers.ts
Beginning to add tests for our number utility (and fixing bugs along the way). This will help us have better test coverage and find issues with the number functions.
> Adding initial number tests

- shared/src/util/Numbers.test.ts
- shared/src/util/Numbers.ts
Improving the coverage of our number tests.
> Adding more number tests

- shared/src/util/Numbers.test.ts
- shared/src/util/Numbers.ts
Further improving the test coverage of our number tests.
> Adding even more number tests

- shared/src/components/common/Input.tsx
As the title indicates, fixing a css input error.
> Fixing css input error

- shared/src/components/common/Input.tsx
Since the keypress event is deprecated, I opted to switch to keydown (with some slight modifications to the logic).
> Moving to keydown (from keypress)

- earn/.github/workflows/sentry-release.yml
Adding a workflow that enables automatic Sentry releases to be created.
> Adding sentry release flow for Earn

- earn/.gitignore
- earn/package.json
- earn/src/index.tsx
- earn/src/scripts/gitInfo.js
- earn/tsconfig.json
Working towards getting automated Sentry releases.
> Adding script to get git commit sha

- .github/workflows/sentry-release-earn.yml
Attempting to get Sentry release automation working
> Moving workflow to root dir

- .github/workflows/sentry-release-prime.yml
- prime/.gitignore
- prime/package.json
- prime/src/index.tsx
- prime/src/scripts/gitInfo.js
- prime/tsconfig.json
Adding sentry release workflow for prime.
> Adding sentry release automation to prime

- prime/src/util/Uniswap.ts
> Removing unused import

- earn/src/index.tsx
- prime/src/index.tsx
Updating the sample rate for Sentry.
> Updating the sample rate

- prime/src/components/borrow/actions/AloeAddMarginActionCard.tsx
- prime/src/components/borrow/actions/AloeBorrowActionCard.tsx
- prime/src/components/borrow/actions/AloeRepayActionCard.tsx
- prime/src/components/borrow/actions/AloeWithdrawActionCard.tsx
Fixing number inputs causing parsing errors with GN.
> Fixing inputs on prime

- shared/src/components/common/Card.tsx
- shared/src/components/common/Divider.tsx
- shared/src/components/common/Input.tsx
- shared/src/components/common/Modal.tsx
- shared/src/data/constants/Colors.ts
Starting to add more colors to constants.
> Adding more color constants

- earn/src/components/portfolio/LendingPairPeerCard.tsx
- earn/src/data/hooks/UseNumberOfUsers.ts
Moving the logic that fetches the number of users per pool to a hook
> Adding number of users hook

- prime/src/components/borrow/ManageAccountTransactionButton.tsx
- prime/src/data/constants/Values.ts
> Moving ante to constants

- earn/src/pages/LendPage.tsx
Removing console log that mistakenly got added.
> Removing console log

- earn/src/components/borrow/UniswapPositionList.tsx
Adding a key to the uniswap position list items to remedy a warning.
> Adding key to uniswap positions list

- earn/package.json
- prime/package.json
- yarn.lock
Bumping recharts version to the most recent release.
> Bumping recharts version

- earn/package.json
- prime/package.json
- shared/package.json
- yarn.lock
I am bumping the prettier version to the latest release.
> Bumping prettier version

- shared/src/components/common/Card.tsx
> Fixing card css

- earn/src/App.tsx
- earn/src/assets/svg/chevrons_up.svg
- earn/src/components/lend/OptimizeButton.tsx
- earn/src/components/lend/SupplyTable.tsx
- earn/src/pages/MarketsPage.tsx
- shared/src/components/common/Typography.tsx
Adding the first component to the new markets page. As of now, this component is not fully complete but will be in future PRs. The goal is to get something out initially and continue to build off of it and improve it.
> Beginning to add the new markets page

- earn/src/components/common/TokenIconsWithTooltip.tsx
- earn/src/components/lend/SupplyTable.tsx
- shared/src/components/common/TokenIcon.tsx
- shared/src/components/common/TokenIcons.tsx
Fixing UI-related bugs such as scrunched icons, line wrapping, and so on.
> Cleaning up supply table styling

- .github/workflows/test-earn.yml
- .github/workflows/test-shared.yml
- earn/package.json
- earn/src/components/lend/OptimizeButton.spec.tsx
Adding our first react test to earn.
> Adding react tests

- earn/src/components/lend/CollateralTable.tsx
- earn/src/components/lend/SupplyTable.tsx
Cleaning up some of the styling of the various tables.
> Cleaning up the styling on the markets page

- shared/src/components/navbar/ChainSelector.tsx
Fixing a bug with the chain selector styling which caused it to not render below the button.
> Fixing chain selector

- earn/src/components/lend/CollateralTable.tsx
Only showing the collateral table if there are rows to show.
> Cleaning up collateral table styling

- earn/src/components/boost/LiquidityChart.tsx
- earn/src/components/boost/LiquidityChartTooltip.tsx
It wasn't going all the way to the right.
> Fixing boost tooltip

- earn/src/components/boost/BoostCardPlaceholder.tsx
- earn/src/pages/BoostPage.tsx
Adding a placeholder for the boost card.
> Adding boost card placeholder

- prime/src/components/graph/PnLGraph.tsx
- prime/src/components/graph/PnLGraphPlaceholder.tsx
Improving the pnl graph placeholder by making it match the sizing of the real component.
> Cleaning up pnl graph placeholder

- earn/src/components/boost/LiquidityChart.tsx
> Improving styling of active dot

- earn/src/components/boost/BoostCard.tsx
- earn/src/components/boost/ManageBoostModal.tsx
- earn/src/pages/BoostPage.tsx
Adding the foundation for the manage boost modal. There is still more work to be done on it.
> Adding manage boost modal

- earn/src/components/borrow/modal/WithdrawUniswapNFTModal.tsx
- earn/src/components/borrow/modal/tab/AddUniswapNFTAsCollateralTab.tsx
- earn/src/components/header/Header.tsx
- prime/src/components/borrow/ManageAccountTransactionButton.tsx
Adding some final touches before deploying on base
> Fixing bugs and preparing to launch on base

- earn/src/components/boost/ImportModal.tsx
- earn/src/data/Uniboost.ts
- earn/src/data/Uniswap.ts
- earn/src/pages/BoostPage.tsx
- shared/src/abis/BoostNFT.ts
@IanWoodard this isn't done; feel free to work off of it.
> Scaffolding for approve+import transaction

- earn/src/components/boost/LiquidityChartTooltip.tsx
Avoiding unnecessary stylesheet generation.
> Fixing tooltip styling

- earn/src/components/boost/LiquidityChart.tsx
> Adding icons to at the bounds

- earn/src/components/boost/BoostCard.tsx
- earn/src/components/boost/ImportModal.tsx
- earn/src/components/boost/LiquidityChart.tsx
- shared/src/data/hooks/UseDebouncedMemo.ts
> Adding liquidation thresholds to boost graph

- earn/src/components/boost/ManageBoostModal.tsx
- earn/src/pages/BoostPage.tsx
> Implementing manage modal

- earn/src/components/boost/ManageBoostModal.tsx
Updating the text so we don't forget to fix it later.
> Updating text

- earn/src/components/boost/LiquidityChart.tsx
Adding an overlay to the less functional chart when liquidity data is not available (either because there is no subgraph support for that chain or the graph is down).
> Adding error msg when liquidity data can't be loaded

- earn/src/index.tsx
- prime/src/index.tsx
- shared/src/data/constants/SentryEnvironments.ts
This will allow us to differentiate errors that happen in prod vs dev easier.
> Adding sentry environments

- shared/src/data/hooks/UseDebouncedMemo.ts
There were some oversights in the previous version that should be fixed now.
> Improving the useDebouncedMemo hook

- earn/src/components/boost/ManageBoostModal.tsx
- earn/src/pages/BoostPage.tsx
By making cardInfo required, a lot of the logic is simplified.
> Cleaning up manage boost modal

- earn/src/App.tsx
- earn/src/pages/boost/ManageBoostPage.tsx
Adding the foundations for a new manage boost page.
> Adding manage boost page

- earn/src/components/boost/CollectFeesWidget.tsx
- earn/src/pages/boost/ManageBoostPage.tsx
- shared/src/data/constants/Colors.ts
- shared/src/util/Numbers.test.ts
- shared/src/util/Numbers.ts
> Adding collect fees widget

- earn/src/data/Uniboost.ts
> No more NaN

- earn/src/components/boost/BoostCard.tsx
- earn/src/pages/BoostPage.tsx
Moving from using buttons to using links for the boost card.
> Adding boost links

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/pages/boost/ImportBoostPage.tsx
Adding minting functionality to the import boost page. It is worth noting that the styling is not finished and this PR is merely meant to get the functionality out there.
> Adding import boost widget

- earn/src/data/Uniswap.ts
- earn/src/util/GraphQL.ts
By allowing and subsequently ignoring errors, we are able to bypass the graph errors.
> Fixing the graph on optimism

- earn/src/components/boost/ImportBoostWidget.tsx
This is an incremental step towards providing a better UX. In the future we should give more specific information about why they can't mint.
> Adding logic to detect when the user is unable to mint and show them

- earn/src/App.tsx
- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/pages/BoostPage.tsx
- earn/src/pages/boost/ImportBoostPage.tsx
- earn/src/pages/boost/ManageBoostPage.tsx
- shared/src/data/hooks/UseChainDependentState.ts
- shared/src/data/hooks/UseSafeState.ts
Added a `useSafeState` hook to help reduce the amount we use "isMounted" in our code as using the `useSafeState` hook checks that the component is mounted before setting state. I only began rolling it out across our codebase to get a sense of what it would look like.
> Adding useSafeState hook

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/pages/boost/ImportBoostPage.tsx
Removing the hypothetical card info from the import boost widget.
> Fixing import boost

- earn/src/components/boost/ImportBoostWidget.tsx
I accidentally broke this functionality in a previous PR.
> Fixing import boost page summary

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/data/Uniswap.ts
- earn/src/util/GraphQL.ts
> Adding estimated daily fees to import boost page

- earn/src/pages/BoostPage.tsx
- earn/src/pages/boost/ImportBoostPage.tsx
- earn/src/pages/boost/ManageBoostPage.tsx
- shared/src/assets/svg/ArrowLeft.tsx
> Adding back button to boost pages

- earn/src/components/boost/ImportBoostWidget.tsx
> Updating import boost page summary

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/components/borrow/ManageAccountButtons.tsx
- earn/src/components/borrow/modal/BorrowModal.tsx
- earn/src/components/borrow/modal/WithdrawAnteModal.tsx
- earn/src/pages/BorrowPage.tsx
There is still some more work to be done potentially with regard to when the button is disabled, but this is meant as a starting point.
> Adding withdraw ante modal

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/pages/boost/ImportBoostPage.tsx
> Updating import boost page styling

- earn/src/App.tsx
- earn/src/pages/InfoPage.tsx
> Adding info page

- earn/src/App.tsx
- earn/src/components/header/Header.tsx
- earn/src/pages/InfoPage.tsx
@IanWoodard I added the necessary fields to the data struct, hoping you can do the rest here. Goal is this:
> Add functionality to the info page

- earn/src/components/info/MarketCard.tsx
- earn/src/pages/InfoPage.tsx
- shared/src/assets/svg/Open.tsx
> Adding initial market card to stats page

- earn/src/pages/BorrowPage.tsx
Currently, the first margin account is selected whenever you refresh the page. With this change, it remembers previously selected ones when you refresh.
> Adding selected margin account as search param

- earn/.eslintrc
- earn/src/components/info/LenderCard.tsx
- earn/src/components/info/MarketCard.tsx
- earn/src/data/constants/Values.ts
- earn/src/pages/InfoPage.tsx
> Adding lender card to stats page

- earn/src/components/info/MarketCard.tsx
- earn/src/pages/InfoPage.tsx
- shared/src/abis/Factory.ts
> Adding pause functionality to info page

- earn/src/components/borrow/BorrowGraphPlaceholder.tsx
- earn/src/components/borrow/BorrowMetrics.tsx
- earn/src/components/borrow/SmartWalletButton.tsx
- earn/src/pages/BorrowPage.tsx
Also stopped other loading animations if/when the page realizes the user has no accounts.
> Animate create smart wallet button when user has no accounts

- earn/src/components/boost/NoPositions.tsx
- earn/src/pages/BoostPage.tsx
> Adding a state when user has no positions on boost

- earn/src/components/lend/SupplyTable.tsx
- earn/src/components/lend/modal/SupplyModal.tsx
- shared/src/components/common/TokenIcons.tsx
This is subject to change and is merely a first iteration.
> Adding initial supply modal

- shared/src/components/navbar/NavBar.tsx
Fixing a bug that caused dead zones where the navbar would not render properly.
> Fixing long standing navbar bug

- earn/src/components/info/MarketCard.tsx
- earn/src/pages/InfoPage.tsx
Fixing bug with disabled state of updateLTV button in market card. Adding PendingTxnModal to stats page.
> Fixing market card, adding pendingTxnModal

- shared/package.json
- shared/src/assets/svg/Bell.tsx
- shared/src/components/navbar/AccountInfo.tsx
- shared/src/data/constants/Values.ts
- yarn.lock
Adding the flow for a user to set up liquidation notifications.
> Adding notification service link

- earn/src/components/lend/SupplyTable.tsx
> Temporarily remove optimize button

- earn/src/components/lend/BorrowingWidget.tsx
- earn/src/pages/MarketsPage.tsx
> Restyling borrowing widget

- earn/src/components/lend/BorrowingWidget.tsx
This aims to make the colors more consistent across the supply, collateral, and borrow sections.
> Fixing color of row on hover

- earn/src/data/Uniboost.ts
- earn/src/pages/boost/ManageBoostPage.tsx
Fixing a bug that caused the tokenPtr to not always be set after loading.
> Adding a proper fix to the updating of tokenPtr

- earn/src/components/lend/SupplyTable.tsx
- earn/src/components/lend/modal/SupplyModal.tsx
- earn/src/pages/MarketsPage.tsx
Re-using most of the logic from the `EarnInterestModal`.
> Adding deposit logic to markets page

- earn/src/components/lend/BorrowingWidget.tsx
- earn/src/components/lend/modal/BorrowModal.tsx
- earn/src/data/LendingPair.ts
- shared/src/data/TokenData.ts
> Adding borrow modal to markets page

- earn/src/components/lend/BorrowingWidget.tsx
Fixing the color of the text in the borrowing widget.
> Fixing coloring

- earn/src/components/lend/modal/BorrowModal.tsx
> Adding insufficient ante state

- earn/src/components/lend/BorrowingWidget.tsx
Removing overly complex components. I will replace them with something more fitting soon.
> removing overly complex components

- earn/src/components/lend/SupplyTable.tsx
- earn/src/components/lend/modal/WithdrawModal.tsx
- earn/src/pages/MarketsPage.tsx
> Adding withdraw modal to markets page

- earn/src/components/boost/ImportBoostWidget.tsx
- earn/src/data/BorrowerNft.ts
- earn/src/pages/BoostPage.tsx
- shared/src/util/Arrays.ts
> Simplifying borrower nft code

- earn/src/components/lend/SupplyTable.tsx
- earn/src/pages/MarketsPage.tsx
- shared/src/data/hooks/UseSortableData.ts
> Adding sorting to supply table

- earn/src/components/lend/modal/BorrowModal.tsx
Some incremental improvements to the borrow modal on the new markets page
> Cleaning up the borrow modal

- earn/src/components/lend/modal/UpdateBorrowerModal.tsx
- earn/src/components/lend/modal/content/AddCollateralModalContent.tsx
- earn/src/components/lend/modal/content/RemoveCollateralModalContent.tsx
- earn/src/components/lend/modal/content/RepayModalContent.tsx
- earn/src/data/BorrowerNft.ts
Fixing some bugs and adding missing implementation.
> Improving markets page modals

- earn/src/components/lend/modal/content/BorrowModalContent.tsx
- shared/src/components/common/Tooltip.tsx
> Adding health bar to borrow modal for borrowing widget

- earn/src/components/lend/modal/content/RepayModalContent.tsx
> Adding health bar to repay modal

- earn/src/components/lend/modal/BorrowModal.tsx
Adding footer to borrow modal on markets page
> Updating borrow modal

- earn/src/components/lend/modal/content/BorrowModalContent.tsx
Adding a better summary of the action.
> Improving UX of borrow modal content

- earn/src/components/lend/modal/content/RepayModalContent.tsx
Adding a better summary of the action.
> Improving UX of repay modal content

- earn/src/components/lend/modal/content/BorrowModalContent.tsx
Updating the borrow modal content to use input that specifies 80% Max.
> Tweaking borrow modal content

- earn/src/App.tsx
- prime/src/App.tsx
- shared/src/components/common/AccountBlockedModal.tsx
- shared/src/data/AccountRisk.tsx
- shared/src/data/constants/Values.ts
- shared/src/data/hooks/UseAccountRisk.ts
Setting up the foundation for screening addresses.
> Adding account risk screening

- earn/src/components/lend/modal/content/RepayModalContent.tsx
Will need different solution once we're chaining things, but this works for now.
> Use Router's repay method to repay max on Fuse2 BorrowerNFTs

- earn/src/App.tsx
- earn/src/pages/CountdownPage.tsx
- shared/src/data/constants/Values.ts
This page includes a countdown to launch and a glitch effect to add some pizzaz.
> Adding countdown page

- prime/src/App.tsx
- prime/src/pages/ComingSoonPage.tsx
> Adding coming soon page to prime

- earn/src/App.tsx
Adding an env var to bypass the countdown till launch
> Adding explicit countdown bypass and debug log

- earn/src/components/lend/BorrowingWidget.tsx
- earn/src/components/lend/modal/BorrowModal.tsx
> Adding estimated APR to borrow modal

- earn/src/App.tsx
- shared/src/components/banner/LaunchBanner.tsx
> Adding launch banner

- earn/src/pages/LeaderboardPage.tsx
Fixing ENS for the leaderboard page.
> Fixing ENS

- earn/src/App.tsx
- earn/src/components/header/Header.tsx
- earn/src/components/portfolio/LendingPairPeerCard.tsx
- earn/src/components/portfolio/TokenSearchInput.tsx
- earn/src/data/constants/Values.ts
- earn/src/pages/LeaderboardPage.tsx
- earn/src/pages/PortfolioPage.tsx
- shared/src/components/common/Dropdown.tsx
- shared/src/components/common/Pagination.tsx
- shared/src/components/navbar/ChainSelector.tsx
- shared/src/components/navbar/NavBar.tsx
- shared/src/data/constants/Values.ts
> Show user points in NavBar and remove LaunchBanner

- earn/src/components/lend/BorrowingWidget.tsx
> Separate tables for active/available borrows on Markets>Borrow

- earn/src/components/lend/modal/content/AddCollateralModalContent.tsx
Updating the logic in the add collateral modal content to use the correct collateral balance.
> Fixing collateral amount calc

- earn/src/components/header/Header.tsx
- prime/src/components/header/Header.tsx
Didn't fix every usage of geo-fencing last time around, this should cover the rest.
> Fixing geo-fencing smore

- earn/src/pages/BorrowPage.tsx
This is the same technique I used for the "Monitor" tab of the Markets page. Fetching the exact timestamp for every log is infeasible, so we linearly interpolate timestamps between the first and last block.
Note that we were _already_ doing linear interpolation to get equally-spaced points for _displaying_ the chart (since Dates are categorical for recharts purposes), so this doesn't really change the accuracy of user-facing data.
> Eliminate 1000's of requests on Advanced page using smarter timestamps

- earn/src/components/markets/supply/SupplyTable.tsx
- earn/src/pages/MarketsPage.tsx
- shared/src/data/constants/ChainSpecific.tsx
> Adding metrics to markets page

- prime/src/components/borrow/MarginAccountCard.tsx
- prime/src/data/constants/Values.ts
> Removing unused variables

- earn/src/components/markets/borrow/BorrowingWidget.tsx
Prevents the active borrowers section from showing up when it shouldn't
> Filter borrowers to prevent blank positions

- earn/src/components/advanced/UniswapPositionList.tsx
> Fixing grey button on advanced page

- earn/src/components/markets/modal/BorrowModal.tsx
Fixing bug with index logic due to using not rather than checking if undefined directly.
> Fixing not index logic

- earn/src/pages/MarketsPage.tsx
This PR enables users to remain on the same tab on the markets page when they refresh.
> Adding selectedTab search param

- earn/src/components/common/ApyWithTooltip.tsx
- earn/src/components/markets/monitor/InfoGraphTooltip.tsx
- earn/src/components/markets/supply/SupplyTable.tsx
- earn/src/pages/MarketsPage.tsx
> Don't try to display points until we have price data

- earn/src/App.tsx
- prime/src/App.tsx
Tagging the chain in Sentry allows us to see which issues impact which chains.
> Tagging chain in Sentry

- .github/workflows/test-earn.yml
- .github/workflows/test-prime.yml
- .github/workflows/test-shared.yml
- earn/package.json
- prime/package.json
- shared/package.json
- shared/src/components/WagmiProvider.tsx
Hopefully turning off shimDisconnect should fix some connection issues causing wallets to randomly disconnect. Also, updating node version.
> Bumping node version, turning off shimDisconnect

- shared/src/util/Numbers.test.ts
- shared/src/util/Numbers.ts
Adjusting how we format token amounts to show more information without sacrificing screen space.
> Making token amount formatting smarter

- earn/src/components/markets/supply/SupplyTable.tsx
- earn/src/index.css
- shared/src/components/common/Buttons.tsx
- shared/src/components/navbar/ConnectWalletButton.tsx
This is pretty hacky but it works.
> Enable supply buttons when wallet is disconnected

- earn/src/components/markets/modal/SupplyModal.tsx
Forgot to include this in previously merged change
> Removing unused code from previous PR

- earn/src/components/markets/borrow/BorrowingWidget.tsx
This change addresses an edge case that rarely occurs.
> Improving borrow entry logic
