earn/src/components/portfolio/modal/EarnInterestModal.tsx, earn/src/components/portfolio/modal/SendCryptoModal.tsx, earn/src/components/portfolio/modal/WithdrawModal.tsx
A long overdue update to the portfolio page stops the page from fetching data from within the modal unless that modal is open. This saves us a lot of requests as this not only happened on each initial render but also when users hovered over a different asset.
=> Adding condition to stop unnecessary fetches

earn/src/components/portfolio/LendingPairPeerCard.tsx, earn/src/components/portfolio/modal/EarnInterestModal.tsx, earn/src/components/portfolio/modal/SendCryptoModal.tsx, earn/src/components/portfolio/modal/WithdrawModal.tsx, earn/src/pages/BorrowPage.tsx
Building off of #312, this PR adds caching that prevents the unnecessary re-fetching of data for lending pairs. This also saves us a fair bit of outgoing requests and is a great optimization.
=> Adding caching for lender pair data

earn/src/components/borrow/ManageAccountButtons.tsx, earn/src/components/borrow/modal/AddCollateralModal.tsx, earn/src/components/borrow/modal/BorrowModal.tsx, earn/src/components/borrow/modal/RemoveCollateralModal.tsx, earn/src/components/borrow/modal/RepayModal.tsx, earn/src/pages/BorrowPage.tsx
As the title suggests, I am adding the remainder of the modals to the earn borrow page and implementing the add collateral modal. The rest are waiting on some contracts to get deployed. Here is an image of the add collateral modal:
=> Adding the rest of the modals to the earn borrow page

earn/src/components/portfolio/LendingPairPeerCard.tsx
I am unsure if there are many downsides to not providing a reasonable fromBlock. I would like to know if it has any noticeable effect on the time it takes us to receive a response. If that is the case, we should use more precise numbers, which enables this to work cross-chain for now. We will likely not know for sure if there is much of any effect right now because we aren't fetching too much data, but as this amount grows, the impact may be more noticeable.
=> Switching from block to zero to work cross chain

earn/package.json, earn/src/data/MarginAccount.ts, earn/src/pages/BorrowPage.tsx, earn/src/util/Multicall.ts, yarn.lock
Multicall allows us to combine multiple calls that would otherwise be sent separately, which helps us reduce the number of outgoing requests we need to send to populate the data on the page. This PR switches some of our existing fetches to use multicall. There is still plenty more work to be done in future PRs.
=> Starting to add multicall to optimize our requests

earn/src/components/borrow/modal/BorrowModal.tsx
Making the terminology more consistent throughout the web app. @haydenshively is already replacing the other instance of this in the Repay modal.
=> Replacing liability term with borrows

earn/src/components/borrow/GlobalStatsTable.tsx, earn/src/data/MarginAccount.ts, earn/src/pages/BorrowPage.tsx, earn/src/util/Multicall.ts
As the title suggests, this PR aims to remove margin account previews from earn so that we can instead fetch all of the margin accounts simultaneously using a multicall. I also worked on improving the robustness and quality of our handling of the multicall data.
=> Removing margin account previews from earn

earn/src/components/borrow/GlobalStatsTable.tsx, earn/src/components/borrow/modal/AddCollateralModal.tsx, earn/src/components/borrow/modal/BorrowModal.tsx, earn/src/components/borrow/modal/RemoveCollateralModal.tsx, earn/src/components/borrow/modal/RepayModal.tsx, earn/src/data/MarginAccount.ts, earn/src/pages/BorrowPage.tsx, earn/src/util/Multicall.ts
Builds off of #321. Currently, no logic updates the selectedToken to match the selected margin account, leading to less-than-desirable results, such as having a selectedToken that isn't even a part of the selected pair. With this new logic, there is also no need to reset the modal explicitly on close as we did before.
=> Fixing modal state updating

earn/src/components/borrow/modal/RepayModal.tsx, earn/src/util/Numbers.ts
Fixing a bug that caused the repay modal to crash when the amount was small enough, and javascript decided to represent it in scientific notation in the toString result. To fix this, I added a function that removes scientific notation from a number (if a number is in scientific notation) and clamps that number to no more than a certain amount of decimals provided as input.
=> Fixing scientific notation breaking decimals

earn/src/components/portfolio/modal/EarnInterestModal.tsx
This PR addresses an old bug that unintentionally causes the deposit button to switch states (from pending). The logic we had worked fine for normal transactions but did not work as intended for permit and approve. This PR aims to fix that.
=> Fixing earn interest modal logic

earn/src/App.tsx, shared/src/components/common/WelcomeModal.tsx
When the user clicks "skip for now" on the welcome modal on earn, they are brought to the markets page.
=> skip to the markets page on earn

prime/src/components/borrow/actions/UniswapRemoveLiquidityActionCard.tsx
I noticed that there was quite a bit of delay from when I typed in a number on the remove liquidity action card (and then clicked off the input) and when it formatted the number. In the past, this update happened immediately, but this logic must have gotten removed at some point. I fixed this issue by adding the `userInputFields` to the list of dependencies. It is a very small fix, but it makes a huge difference in UX.
=> Fix remove liquidity percentage not snapping on blur

earn/src/components/borrow/BorrowMetrics.tsx, earn/src/data/BalanceSheet.ts, earn/src/data/Uniswap.ts, earn/src/pages/BorrowPage.tsx
As the title suggests, I am passing the uniswap positions into the calculations for the liquidation thresholds to get a more accurate result. Additionally, I am fixing a few bugs along the way.
=> Passing uniswap positions into liquidation threshold calculations

prime/src/pages/BorrowActionsPage.tsx
Fixing a bug that caused prime to crash when there was no utilization. This happened because we used a nullish coalescing operator (`??`) instead of a logical or (`||`). The reason this matters, in this case, is that the value that was causing us trouble, `NaN`, is not null or undefined and thus is not considered nullish. Therefore, instead of defaulting the value of zero, `NaN` was kept. However, since `NaN` is considered falsy, the value would default to zero, as it should. Moreover, I also added additional logic at the source of the `NaN`, which happened due to a division by zero, so that it should no longer produce a `NaN` value going forward. With that said, I decided to be extra cautious and still switched from a nullish coalescing operator in this case to a logical or just-in-case. …
=> Fixing bug that caused prime to crash

earn/src/data/LendingPair.ts, earn/src/data/MarginAccount.ts, earn/src/util/Numbers.ts, prime/src/data/MarginAccount.ts, prime/src/data/MarketInfo.ts, prime/src/util/Numbers.ts
Sometimes the health computed by the borrower lens was larger than Javascript could handle, resulting in Prime page crashing.
Also, the health on the earn Borrow page was not being divided by 1e18.
I added a new util function to make things clearer. Both issues are fixed now.
=> Util function to avoid mistakes+overflows when fetching chain data

shared/src/assets/svg/Menu.tsx, shared/src/components/common/Footer.tsx, shared/src/components/navbar/AccountInfo.tsx, shared/src/components/navbar/NavBar.tsx, shared/src/data/hooks/UseLockScroll.ts
Adding a more responsive system for phones, tablets, laptops, and desktops. While this PR adds a bit of complexity to the navbar component, it also enables a better UX as it ensures we provide a navigation interface that works well with just about any device a user may have. On a very narrow screen, such as a phone, the navbar collapses into a menu button. The user can click a menu button at the bottom left of the screen, which is a good placement for users on mobile devices, which, when clicked, opens a full-screen nav drawer that allows users to see and click links that are better suited for use with fingers. When it comes to tablets, we now use what was previously meant to be used with phones, which is the interface with the navbar links moved to the bottom for easier access and so …
=> Adding mobile version of the navbar

earn/src/components/borrow/UniswapPositionList.tsx, earn/src/components/borrow/modal/WithdrawUniswapNFTModal.tsx, earn/src/data/Uniswap.ts, earn/src/pages/BorrowPage.tsx
Added Uniswap position list to the earn borrow page. Fixed bugs involving fetching, manipulating, and displaying Uniswap positions. Added the ability to withdraw imported Uniswap positions back to the Uniswap NFT. Below are some images of the updated components:
=> Adding uniswap positions to earn borrow page and added withdraw

earn/src/util/Etherscan.ts, prime/src/util/Etherscan.ts
As the title suggests, Etherscan just made it so that we need separate API keys for optimism and mainnet leading us to update our code accordingly. Netlify should already have the new API keys in the env variables. Once merged, we just need to switch the normal Etherscan API key back (since I switched it to mitigate the issue initially).
=> Fixing etherscan on optimism

earn/src/pages/BorrowPage.tsx
We should have used the denylist on the earn borrow page to add a new smart wallet. This PR addresses that issue.
=> Fixing denylist on earn's borrow page

earn/src/assets/svg/tokens/magic.svg, earn/src/assets/svg/tokens/mim.svg, prime/src/assets/svg/tokens/magic.svg, prime/src/assets/svg/tokens/mim.svg
Fixing the same firefox bug from #294. I forgot about this and neglected to specify widths and heights for the SVGs causing errors on Firefox. This PR aims to fix that.
=> Fixing firefox bug for the second time since I forgot it existed

earn/src/assets/abis/Router.json, earn/src/components/borrow/modal/RepayModal.tsx
We recently updated the address but forgot to update the code and ABI to utilize `repayWithApprove` rather than `repay`. This PR updates the code and ABI accordingly to match the deployed contract.
=> Fixing repayWithApprove

earn/src/components/lend/LendPairCard.tsx, earn/src/components/lend/LendTokenInfo.tsx, earn/src/util/Numbers.ts
Currently, the formatting for amounts on the market page is inconsistent and error-prone. This PR aims to address most of the issues, especially those involving the overflow of amounts on the markets page. This new approach involves mapping amounts into three categories, abbreviated, normal, and scientific notation. Abbreviated is for numbers bigger than a certain threshold, currently 10,000, and abbreviated the amounts using K to denote thousand, M to denote million, B to denote billion, and so on. Normal numbers are those that are not too small or too large and, with a bit of truncating, can be shown easily. Lastly, scientific notation is used to format numbers smaller than a certain threshold, currently 10^-4, so that we don't end up with needlessly long numbers that describe extremely …
=> Adding a better formatting function for the market card

earn/src/components/borrow/HealthBar.tsx, earn/src/components/borrow/modal/BorrowModal.tsx
As the title suggests, I am adding a health bar to the borrow modal to show users what their health will look like after borrowing. Assuming it looks good, I plan to add this to the other modals (where need be). Along with the new health bar, I also cleaned up the logic that handles when the contract gets prepared and added new button states to give the user a more accurate description of the current state. Below is an image of the updated modal:
=> Adding a healthbar to borrow modal

earn/src/components/borrow/modal/RepayModal.tsx, earn/src/pages/BorrowPage.tsx
As the title suggests, I am adding the health bar to the repay modal to show the user what their health will be upon repaying to help users understand how to make their account healthier. The styling is the same as the other modals.
=> Adding health bar to repay modal on earn

prime/src/components/borrow/actions/UniswapAddLiquidityActionCard.tsx, prime/src/components/borrow/uniswap/LiquidityChartNotAvailable.tsx
Currently, if there is no data for the liquidity chart, as is the case on Arbitrum, the chart will load indefinitely. This can lead to confusion among users as it is unclear what is happening. To address this, I made it so that the chart will disappear instead of loading forever if there is no chart data for a specific pool. Below is an image of the updated component:
=> Adding error msg if liquidity chart doesn't have data

earn/src/components/borrow/UniswapPositionList.tsx
Currently, if the total value of a Uniswap position is zero, the percentages of each asset will show `NaN`. This PR addresses that by making the percentages zero in this case.
=> Fixing NaN for uniswap position

earn/src/data/MarginAccount.ts, earn/src/pages/BorrowPage.tsx
While I am not completely satisfied with how this looks, I think it is a good start and enables users to navigate to their smart wallet on Etherscan more easily. The link will use the correct block explorer for the active chain.
I added separate styling for mobile and desktop:
=> Adding etherscan link to borrow page on earn

earn/src/components/portfolio/modal/WithdrawModal.tsx
Currently, the withdraw modal doesn't handle small values properly because they are sometimes represented in scientific notation. To remedy this, I updated the logic to utilize `Big`'s whenever possible, and when we converted them to strings, I made sure we used `.toFixed()`. Additionally, I added proper gas estimation rather than relying on hardcoded values.
=> Fixing bugs with withdraw and adding gas estimation

earn/src/data/LendingPair.ts
If a full year passes between calls to `accrueInterest`, the previous calculation would be correct. If `accrueInterest` were being called every second, the new calculation would be correct. The true value is somewhere in-between, but the new one is smaller. We'd rather show users an APY that's too small than too large.
=> Fix APY calculation for lending

earn/src/data/RateModel.ts
Capped utilization at 100% in computeYieldPerSecond so that it doesn't give us scientific notation and break things.
=> Cap utilization at 100% in computeYieldPerSecond

earn/src/data/hooks/UseRedeem.ts
Recently, we introduced logic to disable the `convertToShares` fetch if the amount input is greater than the user's balance. While this logic is correct, it didn't take the max button's implementation into account. When the user clicks the max button, we pass Q112 as the amount to indicate the user wants to completely drain the account. However, Q112 is greater than the user's balance causing the `convertToShares` fetch to remain disabled and stopping the entire flow in its tracks. To fix this, I added an additional check for whether the amount is equal to Q112, in which case we enable the `convertToShares` fetch. While this works, I do think we could use a constant that is used by both the logic that sets the max value to Q112 and the check to see if the amount is equal to it so that we …
=> Fixing max withdraw not letting user click

earn/src/components/portfolio/LendingPairPeerCard.tsx, earn/src/data/LendingPair.ts, earn/src/data/MarginAccount.ts, earn/src/pages/BorrowPage.tsx
The etherscan api has been a pain point for us as it has often been slow and even unresponsive at times. Moreover, it is not particularly scalable. This PR aims to start moving our code away from using etherscan and instead to using `eth_getLogs`. The one worry I have with this switch is issues arising from having too many logs and, thus possibly not getting the most updated data or even an error. That is why I chose to leave out the graph data fetching from this PR as it has the potential to grow to a size that may cause issues. Moreover, it does not block the rendering of the page meaning I am less worried about it taking a little longer. I do however hope to come back to this case in the future and properly address it.
I did my best to keep the logic roughly the same as before besides …
=> Starting to remove our etherscan api dependency

earn/src/pages/BorrowPage.tsx
Currently, we show the etherscan link on the borrow page on the Earn site even if no account is selected. This PR addresses this by only showing this link if the user has an account selected.
=> Hiding etherscan link when the user has no margin acount selected

prime/src/components/borrow/MarginAccountHeader.tsx, shared/src/components/common/RoundedBadge.tsx
Updating the prime borrow page to include a link to the associated margin account on Etherscan.
=> Adding etherscan link to prime borrow actions page

earn/src/components/lend/LendPairCard.tsx
Similar to #411, but just disables the button so the user can't open the modal if they don't have a wallet connected.
=> An alternate way of fixing the markets page when not logged in

shared/src/data/GoodNumber.test.ts, shared/src/data/GoodNumber.ts
Added some new functionality to GoodNumbers in preparation for adding it to prime. 
- added the base argument to the `fromDecimalString` and `fromDecimalBig` functions.
- added `one` function to allow the user to easily create a `GN` with a value of 1.
- added `isGteZero`, `isLtZero`, and `isLteZero` as they will be useful.
- added `areWithinNSigDigs` as we use this with numbers that will most likely become `GN`s.
- added tests to get full coverage.
=> Additions to GoodNumbers before adding it to prime

shared/src/util/Utils.ts
Currently, the dappnet code (#426 and #427) causes errors on prime due to window not being defined. This PR aims to fix that by adding an additional check.
=> Fixing window error

shared/src/data/GoodNumber.test.ts
Changing `scaleFor` to `scalerFor`.
=> Fixing typo in test

prime/src/components/borrow/ManageAccountTransactionButton.tsx
Fixing a missed bug where we forgot to update a usage of greater than to use GN.
=> Fixing usage of greater than to use GN

prime/src/util/Uniswap.ts
@IanWoodard's math for this is correct, but quite verbose. His logic did the following:
- convert price to sqrtPriceX96
- use TickMath to convert sqrtPriceX96 to an integer tick _(this floors it)_
- convert that tick back to a price
- compare with original and +/- 1 as necessary to get the _actual_ nearest tick (undo-ing the floor operation from before)
Here, I instead compute a floating point tick and then just `Math.round` it. Output of the function is unchanged.
=> Simplify priceToClosestTick by using JS numbers

prime/src/components/borrow/TokenAllocationPieChartWidget.tsx
Currently, the pie chart on prime has uniswap and raw flipped for token1. This PR aims to fix that.
=> Fixing pie chart on prime to have correct categories

prime/src/components/borrow/TokenAmountSelectInput.tsx, prime/src/components/borrow/TokenDropdown.tsx, prime/src/components/borrow/actions/AloeAddMarginActionCard.tsx, prime/src/components/borrow/actions/AloeBorrowActionCard.tsx, prime/src/components/borrow/actions/AloeRepayActionCard.tsx, prime/src/components/borrow/actions/AloeWithdrawActionCard.tsx
As the title suggests, I am adding a more compact input for the token amounts on the action cards. This component is similar to the one used in some of the newer portfolio modals on earn, but with slight modifications to work with `TokenType` rather than `Token`.
=> Adding more compact token inputs to action cards

earn/src/components/common/TokenChooser.tsx, earn/src/components/lend/LendPieChartWidget.tsx, earn/src/components/portfolio/AssetPriceChartWidget.tsx, earn/src/components/portfolio/LendingPairPeerCard.tsx, earn/src/components/portfolio/SearchBar.tsx, earn/src/pages/LendPage.tsx, prime/src/components/borrow/MarginAccountCard.tsx, prime/src/components/borrow/TokenAllocationPieChartWidget.tsx, prime/src/components/borrow/actions/AloeAddMarginActionCard.tsx, prime/src/components/borrow/actions/AloeBorrowActionCard.tsx, prime/src/components/borrow/actions/AloeRepayActionCard.tsx, prime/src/components/borrow/actions/AloeWithdrawActionCard.tsx, prime/src/components/common/TokenChooser.tsx, prime/src/components/graph/tooltips/PnLGraphTooltip.tsx
Currently, we have a lot of legacy optional usage of token symbols since they used to be optional. Since it is no longer an optional property, I updated the usage to reflect that.
=> Cleaning up symbol usage since it is no longer optional

prime/src/components/borrow/HealthBar.tsx
Currently, the health tooltip does not fit on the screen. This PR fixes it by moving it over.
=> Fixing health tooltip overflow

earn/src/components/borrow/UniswapPositionList.tsx, earn/src/components/borrow/modal/WithdrawUniswapNFTModal.tsx, shared/src/util/Numbers.ts
Fixing some bugs with the formatting of certain numbers.
New:
Old:
=> Cleaning up the number formatting for big numbers

prime/src/components/borrow/AccountNotFound.tsx, prime/src/pages/BorrowActionsPage.tsx
Currently, we do not properly handle the case where the address provided to the actions page does not match an existing borrower. This leads to a blank page and some errors. To address this, I added a new flow that displays a message when an invalid address is provided (often when someone is not using the correct chain for a given address) and added extra checks to prevent certain errors from occurring.
=> Adding account not found state to prime actions page

prime/src/components/borrow/HealthBar.tsx, prime/src/util/Health.ts
Making the health displays consistent across prime. Adding more decimal points in the manage account widget health. Adding text coloring to the manage account widget health. One thing to note is that I did update the max health that the manage account widget displays (as "X+") from 3 to 5 (to match the accounts page); however, I did notice that the health bar relies on the health values to be between 0.5 and 3, so technically any value greater than three shows as the max on the health bar, but doesn't show up as "5+" until a value of 5 is reached. If this doesn't make sense, don't worry about it too much. I just feel it is more important to match between pages. I recommend trying it out for yourself and seeing how it feels. We could also just use "3+" everywhere as an alternate option.
=> Reworking how we display health

earn/src/components/borrow/BorrowMetrics.tsx
As the title suggests, I am adding placeholders (similar to those seen elsewhere) to the borrow metrics on the borrow page for earn. This will allow the component to be visible as it loads in order for there to be less layout shift.
=> Adding placeholder for borrow metrics

earn/src/components/borrow/GlobalStatsTable.tsx
Adding placeholder values for when the pair stats is loading. This helps mitigate layout shifting and improves UX.
=> Adding placeholder for pair stats

earn/src/components/borrow/BorrowGraphPlaceholder.tsx, earn/src/pages/BorrowPage.tsx
Currently, the borrow graph on earn does not show anything while loading and then pops onto the screen when it loads. This can cause some layout shifts. To mitigate this, I added a placeholder for the graph similar to those we used previously.
=> (Earn) Adding placeholder for the borrow graph

shared/src/components/common/Pagination.tsx
Currently, there is a bug with pagination that causes the page to crash when the number of items changes to a smaller number while on a page past one. This happens when the combination of the inputs for the number of items per page and the current page results in you being on a page that no longer exists.
=> Fixing bug with pagination not reseting page

earn/src/data/LendingPair.ts, earn/src/pages/LendPage.tsx
Currently, we do not have any special sorting for the markets page. This PR changes that by sorting the lending cards by apy. The sorting is done by taking the combined average of each lender's apy in the pair.
=> Adding sorting to the markets page (by apy)

prime/src/components/borrow/BorrowSelectActionModal.tsx, prime/src/components/borrow/ManageAccountWidget.tsx, prime/src/components/borrow/SaveTemplateButton.tsx, prime/src/components/borrow/modal/SaveTemplateModal.tsx, prime/src/data/actions/ActionID.ts, prime/src/data/actions/Actions.ts, prime/src/data/actions/StoredActionTemplate.ts, shared/src/data/constants/Colors.ts
Adding the ability to create templates and have them saved locally. I have not implemented a way for existing local templates to be deleted (besides editing local storage manually); this will come soon. Most of the styling in this is subject to change and is just an initial design to get things out.
=> Adding local template functionality

earn/src/pages/PortfolioPage.tsx
Adding logic to clear the portfolio page when the user disconnects their wallet. This prevents the page from looking like the user is still connected when they are not.
=> Clearing portfolio page on disconnect

earn/src/pages/LendPage.tsx
Fixing a bug where changing the filter settings while on a page besides the first can cause the app to crash.
=> Fixing lend page filter bug

earn/src/pages/BorrowPage.tsx, earn/src/pages/PortfolioPage.tsx
Instead of potentially stacking up a bunch of open modals while disconnected, limit the opening of modals to connected accounts.
=> Only show modals when connected

earn/src/pages/PortfolioPage.tsx
Currently, there is a bug that causes us to try to get tokens for the previous chain when switching chains. The logic added in this PR prevents this from happening.
=> Only fetch price relay data when tokens are for correct chain

earn/src/components/header/Header.tsx
Users can access Prime by clicking "Get Leverage" from the borrower page. Renamed "Borrow" tab to "Advanced" since the markets page will soon offer basic borrowing functionality.
=> Remove link to Prime from header

prime/src/pages/BorrowActionsPage.tsx
Currently, we show "ghost" positions that aren't removable.
=> Fixing uniswap table showing empty positions

prime/src/components/borrow/uniswap/UniswapPositionsTable.tsx
Currently, the uniswap positions table on prime does not work well with hypotheticals. I updated the underlying logic to not ignore new uniswap positions (those without fee data).
=> Improving uniswap hypotheticals

earn/src/App.tsx, earn/src/pages/LendPage.tsx, shared/src/components/common/Dropdown.tsx
Adding a wrapper around the dropdown list enables us to add some space between the bottom of the dropdown and the bottom of the page. This has been a long-standing bug. One thing to note is that this does not work if the dropdown is inverted (going upward).
=> Improving the dropdown component

earn/src/App.tsx, earn/src/components/boost/LiquidityChart.tsx, earn/src/components/boost/LiquidityChartTooltip.tsx, earn/src/data/Uniswap.ts, earn/src/pages/BoostPage.tsx
Adding a liquidity chart to the boost cards.
=> Adding liquidity chart

earn/src/components/boost/BoostCard.tsx, earn/src/components/boost/LiquidityChart.tsx, earn/src/components/boost/LiquidityChartTooltip.tsx, earn/src/data/Uniswap.ts, earn/src/pages/BoostPage.tsx, earn/src/util/GraphQL.ts
Liquidity chart now works for positions that span 0 --> infinity
One problem I'm seeing now is when you switch to a different wallet, you have to refresh the page in order for the graphs to refresh properly.
=> Fetch all ticks for liquidity chart

earn/src/components/boost/ManageBoostModal.tsx, shared/src/components/common/Modal.tsx
Improving the styling of the boost modal and adding more styling options to the modal component.
=> Improving styling of boost modal

earn/src/components/boost/LiquidityChartTooltip.tsx
We only want to show infinity on the tooltip if the cursor is all the way to the right (it doesn't make sense for multiple x values to refer to infinity). This fixes that.
=> Fix percentage conditional to avoid premature infinity

earn/src/components/boost/LiquidityChart.tsx
Currently, when liquidity is zero, the computed y position is NaN. This PR makes it so that NaN y positions default to the middle of the chart.
=> Fixing NaN y position

earn/src/components/portfolio/PortfolioMetrics.tsx
=> Making the units for the balance section of portfolio metrics smaller

earn/src/components/boost/ImportBoostWidget.tsx
Previously, we would set it to null if apr0 or apr1 was 0 when we should have only done so if apr0 or apr1 was null.
=> Fixing 1x boost interest calculation

earn/src/components/portfolio/modal/WithdrawModal.tsx
Fixing a long-standing bug that occurred when the user switched tokens after switching to a lending pair whose index is greater than the length of the lending pairs of the newly selected token.
=> Fixing long-standing selected lending pair index bug

.github/workflows/test-earn.yml, .github/workflows/test-prime.yml, .github/workflows/test-shared.yml
Yarn keeps complaining about node-gyp not being installed and recommends that we install it globally.
=> Attempting to fix gh actions

shared/src/components/common/Modal.tsx
Fixing a bug that caused modals' height on smaller screens to extend beyond the screen.
=> Fixing modals on smaller screens

earn/src/data/Uniboost.ts, earn/src/pages/BoostPage.tsx
This is just the initial work required for this. I plan on doing more work to improve this such as adding a UI state when the user doesn't have any imported/importable options. Also, there is still a bug with initially selected chains causing the loading to look a bit wonky, I am planning on looking into that soon. <img width="177" alt="image" src="https://github.com/aloelabs/aloe-frontend/assets/17186604/68ba1159-2fd7-4135-95ae-aa2a07c1f256">
=> Separate imported and importable boost cards

earn/src/components/portfolio/AssetBar.tsx
=> Removing the black border around the token icons in the asset bar

earn/src/components/boost/BurnBoostModal.tsx, earn/src/components/boost/CollectFeesWidget.tsx, earn/src/components/boost/ImportBoostWidget.tsx, earn/src/data/Uniboost.ts, earn/src/data/Uniswap.ts, earn/src/pages/BoostPage.tsx, earn/src/pages/boost/ImportBoostPage.tsx, earn/src/pages/boost/ManageBoostPage.tsx
Updated transaction data for Collect and Burn, and tested it with one position. Only thing missing now is fetching the token's index in the BorrowerNFT array (see TODO on line 121 of `ManageBoostPage`)
There are numerous other improvements to be made, but it's working for now.
- lots of useEffects that don't handle async properly??
- better way of fetching BorrowerNFTs
- use separate data classes for Uniswap NFTs and Boosted Positions
- etc.
=> Fix Boost>Collect and Boost>Burn, now just need dynamic ptr

earn/src/pages/boost/ManageBoostPage.tsx
Currently, there is a bug that causes `tokenPtr` to not always be set causing the burn txn to fail. To fix this, I added an extra check to make sure we don't overwrite the `tokenPtr` value.
=> Fixing bug with tokenPtr not being set

earn/src/components/common/MaxSlippageInput.tsx
Currently, it gets cut off. To fix it, I moved it below the text.
=> Fixing slippage tooltip

earn/src/components/lend/BorrowingWidget.tsx, earn/src/components/lend/modal/BorrowModal.tsx, earn/src/pages/MarketsPage.tsx
Adding `check wallet` states to the borrow modal in the markets page. Also adding pending txn upon confirming borrow.
=> Adding more states to borrow modal

earn/src/components/lend/modal/SupplyModal.tsx
Currently, we don't show an amount in the summary when the user has not input anything. Instead, we should show this amount as zero which this PR does.
=> Always show amount in supply modal

earn/src/data/LendingPair.ts, earn/src/pages/LendPage.tsx, earn/src/pages/MarketsPage.tsx, earn/src/pages/PortfolioPage.tsx
Currently, we do not fetch lending pair balances very efficiently as we do not fully utilize multicall. This PR aims to fix that by using multicall to its full potential, saving us from doing extra calls.
=> Utilizing multicall more when fetching lending pair balances

earn/src/components/lend/modal/content/RepayModalContent.tsx
Currently using loading state in place of disabled when the user has not input a value.
=> Fixing repay modal loading state

earn/src/data/LeaderboardResponse.ts, earn/src/pages/LeaderboardPage.tsx
Currently, the leaderboard does not support ens.
=> Enabling the leaderboard to interface with new API changes for ens

shared/src/components/navbar/NavBar.tsx
Currently, the leaderboard is queried repeatedly in an infinite loop.
=> Fixing perpetual leaderboard queries

earn/src/components/lend/BorrowingWidget.tsx, earn/src/components/lend/SupplyTable.tsx, earn/src/components/portfolio/modal/SendCryptoModal.tsx, earn/src/data/LendingPair.ts, earn/src/pages/LendPage.tsx, earn/src/pages/MarketsPage.tsx, earn/src/pages/PortfolioPage.tsx
When the user clicks on an available borrow asset (right side of the `BorrowingWidget`), I noticed that the collateral entries still show a range of LTVs. Similar to how APYs are narrowed down once you make a selection on the left side, LTVs should be narrowed down once you make a selection on the right side.
With the way things were, this would be very hard to do -- the collateral entries were being pre-computed _outside_ of the `BorrowingWidget` component, and to be honest the multitude of arrays (`LendingPairBalances[]`, `combinedBalances`, `tokenBalances`, etc.) were hard to reason about.
So, to prepare for the `BorrowingWidget` updates I want to make, I refactored how we fetch `LendingPairBalances`. It's fully backwards-compatible with existing logic (so I didn't change this stuff on …
=> Refactor handling of LendingPairBalances (prep for BorrowWidget updates)

earn/src/App.tsx, prime/src/App.tsx, prime/src/components/header/Header.tsx, prime/src/pages/BorrowAccountsPage.tsx, prime/src/pages/BorrowActionsPage.tsx, shared/src/data/GeoFencing.ts, shared/src/data/hooks/UseGeoFencing.ts
Currently, the logic in Prime meant to show that a user is being geo-fenced does not properly. This PR aims to fix that by updating the logic to wait for the geo-fencing request to finish.
=> Fixing geo-fencing message on prime

earn/src/data/hooks/UseAvailablePools.ts, earn/src/pages/MarketsPage.tsx
This is just an efficiency thing. We have all the data we need from `lendingPairs`, so no need to make more requests to get `availablePools`
=> Compute availablePools locally instead of re-fetching them

earn/src/components/lend/BorrowingWidget.tsx, earn/src/components/lend/modal/UpdateBorrowerModal.tsx, earn/src/components/lend/modal/content/BorrowModalContent.tsx
Saves a dozen requests on the Markets page and unifies our logic -- basically everything uses the `lendingPairs` array now.
Some day we should refactor `LendingPair` to have `GN`s instead of plain numbers, but today is not that day.
=> Use lendingPairs instead of fetching duplicate data in marketInfos

earn/src/components/lend/modal/BorrowModal.tsx, earn/src/pages/MarketsPage.tsx
I only did this for normal borrows. Reuse for Uniswap borrows will be a similar, yet separate, PR.
=> Enable reuse of BorrowerNFTs on Markets page

earn/src/data/LendingPair.ts
Currently, there is a bug that causes pages to crash if there is a lending pair with no supply. This change fixes that by ensuring we don't divide by zero.
=> Fixing division by zero

earn/src/data/LendingPair.ts
As the title states, added logic that prevents division by zero by checking if there are no assets before computing borrowAPR.
=> If there are no assets, assume borrowAPR is zero

shared/src/data/TokenData.ts
BALD is currently set on the optimism chain despite being on the base chain, this PR corrects that.
=> Fixing bald base chain

earn/src/data/BorrowerNft.ts
Adding logic to handle and return early the case where there are no lens results when fetching a list of borrower nfts.
=> Handle no lens results

earn/src/components/advanced/BorrowMetrics.tsx
=> Add colored underlines to indicate collateral or borrows

earn/src/components/portfolio/AssetBar.tsx, earn/src/pages/PortfolioPage.tsx
I found myself rarely using the Portfolio page because it almost always showed only a single asset. That was technically correct, percentage-wise, but I wanted to see more. It now shows up to 10 assets, sorted by USD balance, and only slightly varying in size.
Before
After
=> Make AssetBar more useful by showing more tokens

earn/src/components/markets/supply/SupplyTable.tsx
Fixing a bad state that results from switching chains when on a page besides the first on the markets page supply tab.
=> Fixing a bug that causes the markets page to crash

earn/src/components/boost/ImportBoostWidget.tsx
Fixing a bug with the import boost widget's ethToSend calculation causing it to not be mintable.
=> Fixing ethToSend calculations

earn/src/components/portfolio/LendingPairPeerCard.tsx
Added some additional styling to prevent overflowing on the lending pair peer card. In addition to adding this, we should probably also investigate a better technique for figuring out how many sigdigs to use.
Before:
After:
=> Prevent overflow on portfolio page

earn/src/components/boost/BurnBoostModal.tsx, earn/src/components/boost/ImportBoostWidget.tsx, earn/src/components/boost/SlippageWidget.tsx, earn/src/components/common/MaxSlippageInput.tsx, shared/src/util/Numbers.ts
The slippage can be adjusted by clicking on the cog which shows the following menu:
=> Adding slippage for importing boost positions

earn/src/components/advanced/TokenAllocationPieChartWidget.tsx, earn/src/components/advanced/TokenAllocationWidget.tsx, earn/src/pages/AdvancedPage.tsx
This PR adds a token allocation section to the advanced page to show the relative breakdown of the raw tokens vs Uniswap positions.
Wider screens:
Narrower screens:
Empty state:
=> Adding token allocation to the advanced page

earn/src/components/markets/monitor/StatsTable.tsx, earn/src/data/LendingPair.ts, earn/src/data/Slot0.ts
Our oracle needs 60 minutes of data to work right. We require 3 hours of data at pool creation time, but it's possible to stuff the oracle with extra data via wash trading and _shorten the lookback window_. Therefore, I think it's important to surface the actual oracle cardinality on the frontend so users can make even more informed decisions about where to deposit.
=> Add oracle cardinality to Monitor tab

earn/src/components/advanced/modal/BorrowModal.tsx, earn/src/components/advanced/modal/RepayModal.tsx, earn/src/pages/AdvancedPage.tsx
Standard procedure is to immediately send borrowed funds to the user's wallet, and pull from the same in order to repay.
This change allows for an alternate path, where the user borrows but _leaves funds in the NFT_, or (similarly) use funds in the NFT to repay, instead of using funds from their wallet.
This can eliminate a few extra txns depending on the use-case, and will be particularly useful once we allow people to create Uniswap positions through the Advanced page
=> Make borrowed funds dst and repayment src configurable on Advanced page

earn/src/components/markets/monitor/InfoTab.tsx, earn/src/components/markets/monitor/StatsTable.tsx
Fixes the stats tab crashing due to switching chains when on a non-first page.
=> Fixing stats table crashing

earn/src/components/advanced/modal/tab/AddUniswapNFTAsCollateralTab.tsx
Updating the styling to be more inline with the rest of the modals.
**Before:**
**After:**
=> Cleaning up styling of import uniswap modal

earn/src/components/advanced/UniswapPositionList.tsx, earn/src/components/advanced/modal/ImportUniswapNFTModal.tsx, earn/src/pages/AdvancedPage.tsx
Decided to go with a less bland design for the empty state which shows what the position would look like if imported, but with placeholders. To go along with this, I refactored the code to split the component into smaller pieces to avoid code duplication. Additionally, I reused the content of the existing import modal.
Some other potential ideas I have to further improve this design are:
* Adding further visual distinction between the empty and non-empty cards such as opacity when the card is not hovered.
* Adding a better loading state as it currently uses the old empty state as the loading state (when we don't have the borrower information yet).
* Adding a tooltip somewhere to give more information about what it means to import a uniswap position.
* Refactor the import modal to better …
=> Adding Uniswap import button to advanced page

earn/src/components/boost/LiquidityChart.tsx, earn/src/components/markets/liquidate/LiquidateTab.tsx, earn/src/components/markets/liquidate/LiquidateTable.tsx, earn/src/data/BalanceSheet.ts, earn/src/data/Borrower.ts, earn/src/data/MarginAccount.ts, earn/src/data/Uniswap.ts, earn/src/data/constants/Values.ts, earn/src/pages/MarketsPage.tsx, earn/src/util/Addresses.ts, shared/src/abis/BorrowerLens.ts, shared/src/abis/Liquidator.ts, shared/src/data/constants/ChainSpecific.tsx, shared/src/util/Numbers.ts
=> Add liquidate tab to markets page

earn/src/components/common/AddressDropdown.tsx, earn/src/components/markets/modal/RecoverModal.tsx, earn/src/components/markets/modal/WithdrawModal.tsx, earn/src/components/markets/supply/SupplyTable.tsx, earn/src/pages/MarketsPage.tsx, shared/src/abis/BadDebtProcessor.ts
Frontend feature to accompany [this new contract](https://github.com/aloelabs/aloe-ii-examples/blob/606482cf4f227c6b27d8383b5fcac1be65c933b4/src/BadDebtProcessor.sol)
Uses a flash swap to liquidate enough of the bad debt for the user to withdraw. A portion of the withdrawn funds are then used to repay the flash swap (implying a loss -- it is bad debt after all). The user is left with some combination of the original token (WETH) and the unhealthy borrower's collateral (BASED).
Uses Permit with a finite amount because the contract's callback method is unprotected, and could otherwise be manipulated to enable unchecked spending. In other words, **nobody should `approve` the `BadDebtProcessor` non-atomically, and never for infinite spend.**
=> Add recover modal to help users deal with bad debt

earn/src/components/advanced/BorrowGraph.tsx, earn/src/components/markets/borrow/BorrowingWidget.tsx, earn/src/hooks/UseRedeem.ts, earn/src/pages/AdvancedPage.tsx, earn/src/pages/MarketsPage.tsx, earn/src/pages/PortfolioPage.tsx, shared/src/hooks/UseBorrowerNft.ts
Updating wording/styling to improve UX by highlighting what matters and italicizing notes.
=> Addressing some nits in wording
